import { useState } from 'react';
import { Canvas } from '@react-three/fiber';
import { OrbitControls, Environment } from '@react-three/drei';
import { useAgentStore } from '@3d-ai-agent/state';
import { Button } from '@3d-ai-agent/ui';
import { CodeAgent } from '@3d-ai-agent/ai-brain';

// Initialize the Agent
const agent = new CodeAgent(); // Mock mode if no key provided

function Scene() {
  const messages = useAgentStore((state) => state.messages);
  
  // Parse any generated objects from agent messages if they are JSON configs
  const shapes = messages
    .filter((m) => m.role === 'agent' && m.content.includes('"type":'))
    .map((m) => {
      try {
        return JSON.parse(m.content);
      } catch (e) {
        return null;
      }
    })
    .filter(Boolean);

  return (
    <>
      <ambientLight intensity={0.5} />
      <directionalLight position={[10, 10, 5]} intensity={1} />
      <Environment preset="city" />
      <OrbitControls />
      
      {/* Default placeholder shape */}
      {shapes.length === 0 && (
        <mesh>
          <boxGeometry args={[1, 1, 1]} />
          <meshStandardMaterial color="#4f46e5" />
        </mesh>
      )}

      {/* Render shapes generated by the agent */}
      {shapes.map((shape: any, idx: number) => {
        const position: [number, number, number] = [idx * 2, 0, 0];
        if (shape.type === 'box') {
          return (
            <mesh key={shape.id || idx} position={position} scale={shape.scale || 1}>
              <boxGeometry />
              <meshStandardMaterial color={shape.color || '#ffffff'} />
            </mesh>
          );
        }
        if (shape.type === 'sphere') {
          return (
            <mesh key={shape.id || idx} position={position} scale={shape.scale || 1}>
              <sphereGeometry />
              <meshStandardMaterial color={shape.color || '#ffffff'} />
            </mesh>
          );
        }
        if (shape.type === 'torus') {
          return (
            <mesh key={shape.id || idx} position={position} scale={shape.scale || 1}>
              <torusGeometry />
              <meshStandardMaterial color={shape.color || '#ffffff'} />
            </mesh>
          );
        }
        return null;
      })}
    </>
  );
}

function App() {
  const [prompt, setPrompt] = useState('');
  const { messages, addMessage, isThinking, setThinking } = useAgentStore();

  const handleSend = async () => {
    if (!prompt.trim() || isThinking) return;
    
    addMessage({ role: 'user', content: prompt });
    setPrompt('');
    setThinking(true);

    try {
      const response = await agent.run(prompt);
      addMessage({ role: 'agent', content: response });
    } catch (error) {
      addMessage({ role: 'agent', content: `Error: ${error}` });
    } finally {
      setThinking(false);
    }
  };

  return (
    <div className="flex h-screen w-full bg-slate-900 text-slate-50 overflow-hidden">
      {/* Sidebar / Chat Interface */}
      <div className="w-96 flex flex-col border-r border-slate-700 bg-slate-800">
        <div className="p-4 border-b border-slate-700 font-bold text-xl tracking-tight">
          AI 3D Agent Brain
        </div>
        
        <div className="flex-1 p-4 overflow-y-auto flex flex-col gap-3">
          {messages.map((msg, idx) => (
            <div 
              key={idx} 
              className={`p-3 rounded-lg max-w-[85%] ${
                msg.role === 'user' 
                  ? 'bg-blue-600 self-end text-white' 
                  : 'bg-slate-700 self-start text-slate-200'
              }`}
            >
              <span className="text-xs opacity-50 block mb-1 uppercase tracking-wider">{msg.role}</span>
              <div className="text-sm break-words whitespace-pre-wrap font-mono">
                {msg.content}
              </div>
            </div>
          ))}
          {isThinking && (
            <div className="p-3 rounded-lg bg-slate-700 self-start text-slate-400 animate-pulse text-sm">
              Thinking...
            </div>
          )}
        </div>

        <div className="p-4 border-t border-slate-700 bg-slate-800 flex gap-2">
          <input 
            type="text" 
            className="flex-1 bg-slate-900 border border-slate-600 rounded px-3 py-2 text-sm focus:outline-none focus:border-blue-500 transition-colors"
            placeholder="e.g. scaffold a scene with a torus..."
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleSend()}
            disabled={isThinking}
          />
          <Button onClick={handleSend} disabled={isThinking || !prompt.trim()}>
            Send
          </Button>
        </div>
      </div>

      {/* R3F Canvas */}
      <div className="flex-1 relative">
        <Canvas camera={{ position: [0, 2, 5] }}>
          <Scene />
        </Canvas>
        
        <div className="absolute top-4 right-4 pointer-events-none">
          <div className="bg-slate-800/80 backdrop-blur-md px-4 py-2 rounded shadow-lg border border-slate-700 font-mono text-xs text-slate-300">
            Web 3D Viewport
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;
